export const incorrectsDict: { [key: string]: string[] } = {
  can: ["kyan", "con", "kan", "cau"],
  SUPERHERO: ["SUPARHERO", "SUPERHELO", "SUPARHELO"],
  時: ["持", "詩", "刻"],
  君: ["尹", "焄", "黄身", "気味"],
  飛ん: ["跳ん", "翔ん", "㌧", "飛", "乘ん"],
  行く: ["往く", "幾", "術く", "街く"],
  涙: ["泣", "泪", "涅", "沍"],
  似合わ: ["似遭わない", "位合わない", "似合ない", "似泡ない"],
  alright: ["arlight", "alrihgt", "allright", "arrlight"],
  Yes: ["Yez", "Yas", "Yos", "Ys"],
  "365": ["364", "366", "345", "356"],
  days: ["dayz", "bays", "day", "dais"],
  "24": ["23", "25", "42"],
  name: ["neme", "nema", "nome", "nane", "naime"],
  歌っ: ["詩っ", "唄っ", "哥っ", "吟っ"],
  踊っ: ["躍っ", "踏っ", "躍っ", "跳っ"],
  肩: ["型", "肘", "堅", "扉"],
  抜い: ["抜", "縫い", "扶い", "拙い"],
  Won: ["Wan", "Wou", "Wau"],
  long: ["rong", "wrong", "lon", "ron", "lang"],
  愛: ["藍", "受", "哀", "LOVE"],
  希望: ["幾望", "紲望", "奇朢", "稀望", "奇望"],
  思う: ["思もう", "想う", "重う", "念う"],
  分かる: ["分る", "解る", "判る", "和歌る"],
  守り: ["護り", "守もり", "真守り", "守護り"],
  未来: ["未來", "末来", "味蕾", "未米", "禾来"],
  嘘: ["虚", "騙", "嘲", "儘", "偽"],
  Trust: ["Trast", "Tlust", "Trastu", "Trost"],
  trust: ["trast", "tlust", "trastu", "trost"],
  Gimme: ["Gime", "Gimmi", "Gemmi", "Gemme"],
  gimme: ["gime", "gimmi", "gemmi", "gemme"],
  Really: ["Realy", "Raelly", "Realry", "Rearly"],
  really: ["realy", "raelly", "realry", "rearly"],
  You: ["Yon", "Yau", "Yow", "Yoh"],
  alone: ["arone", "aloun", "aroun", "aloned"],
  笑顔: ["絵顔", "咲顔", "笑願", "微笑", "頬笑"],
  強く: ["強よく", "靭く", "弛く", "張く"],
  Call: ["Carr", "Carl", "Calr", "Cale", "Cole"],
  call: ["carr", "carl", "calr", "cale", "cole"],
  聞こ: ["聴こ", "効こ", "問こ", "開こ"],
  雑音: ["難音", "騒音", "喧騒", "雜音", "雑韻", "雑意"],
  Break: ["Bleak", "Braek", "Breck", "Breaking"],
  邪魔: ["妨害", "嫉妬", "邪馬", "雅魔", "邪磨"],
  奴ら: ["双ら", "奴つら", "如ら", "妬ら"],
  Bring: ["Bling", "Brined", "Breng", "Braing"],
  Hang: ["Hong", "Hung", "Hanged", "Hanng", "Haung"],
  Freak: ["Fleak", "Fraek", "Fleek", "Freek", "Frick"],
  Wanna: ["Wonna", "Wunna", "Wanaa", "Wnnaa"],
  Gonna: ["Ganna", "Gunna", "Gonaa", "Gnnoa"],
  辛い: ["空い", "辛らい", "幸い", "辣い"],
  痛い: ["居たい", "痛たい", "疼い", "痒い"],
  預け: ["預ずけ", "譲け", "頼け", "予け"],
  mate: ["mete", "mote", "mata", "maate"],
  Right: ["Light", "Rihgt", "Reght", "Rihgt"],
  言わ: ["云わ", "言", "謂わ", "話わ"],
  未知: ["末知", "道", "未智", "三知"],
  脅威: ["驚異", "協威", "脅異", "脅畏", "恐威"],
  逃げ出さ: ["逃出さ", "遁げ出さ", "奔げ出さ"],
  立ち向かう: ["太刀向かう", "立向かう", "立ち向う", "立向う"],
  明日: ["明後日", "Us", "唱日", "明目"],
  遠く: ["遠おく", "達く", "途く", "逢く"],
  Say: ["Soy", "Sey", "Suy", "Seay", "Saey"],
  聞こえる: ["聞える", "聴こえる", "効こえる", "問こえる", "開こえる"],
  雲: ["蜘蛛", "曇", "霍", "雪"],
  Fly: ["Fry", "Flay", "Fray", "Fley", "Frey"],
  七色: ["虹色", "七式", "Rainbow"],
  Beautiful: [
    "Baeutiful",
    "Beauteful",
    "Beauntiful",
    "Beautifull",
    "Beautyful",
  ],
};
