export const incorrectsDict: { [key: string]: string[] } = {
  can: ["wanna", "gonna", "kan"],
  SUPERHERO: ["SUPARHERO", "SUPERHELO", "SUPARHELO"],
  時: ["刻", "時間"],
  飛ん: ["飛", "跳ん", "翔ん"],
  行く: ["行", "赴く", "往く"],
  涙: ["泣", "泪", "嗚咽"],
  似合わ: ["相応わ", "位合わ", "似合", "釣合わ"],
  alright: ["arlight", "alrihgt", "allright"],
  "365": ["364", "366", "345", "356"],
  days: ["dayz", "deys", "day", "dey"],
  "24": ["23", "25", "42"],
  name: ["neme", "nema", "nane"],
  歌っ: ["詩っ", "唄っ", "吟っ"],
  踊っ: ["躍っ", "踏っ", "舞っ"],
  肩: ["型", "肘", "堅"],
  long: ["rong", "wrong", "loung", "lang"],
  愛: ["恋", "愛情", "哀"],
  希望: ["願望", "祈望", "望み", "欲望"],
  思う: ["思もう", "想う", "懐う", "思起う"],
  分かる: ["分る", "解る", "判る", "和歌る"],
  守り: ["護り", "守もり", "庇い", "守護り"],
  未来: ["将来", "末来", "未頼"],
  信じ: ["信んじ", "震じ", "信頼し"],
  嘘: ["虚", "虚偽", "偽"],
  Trust: ["Trast", "Tlust", "Traste", "Trost"],
  Gimme: ["Gime", "Gimmi", "Gemmi", "Gemme"],
  Really: ["Realy", "Raelly", "Realry", "Rearly"],
  alone: ["arone", "aloun", "aroun", "aloned"],
  笑顔: ["頬笑", "微笑"],
  Call: ["Coll", "Cale", "Cole"],
  聞こ: ["聴こ", "効こ", "訊こ"],
  雑音: ["難音", "騒音", "喧騒"],
  Break: ["Bleak", "Braek", "Breck"],
  邪魔: ["妨害", "阻害", "邪馬"],
  奴ら: ["双ら", "奴つら", "彼奴ら", "連中ら"],
  Bring: ["Bling", "Brined", "Breng"],
  Hang: ["Hong", "Hung", "Haung"],
  Freak: ["Fleak", "Fraek", "Fleek", "Freek"],
  Wanna: ["Wonna", "Wanaa", "Wnnaa"],
  Gonna: ["Ganna", "Gonaa", "Gnnoa"],
  辛い: ["辛らい", "幸い", "痛い"],
  痛い: ["苦しい", "痛たい", "辛い"],
  預け: ["預ずけ", "託して", "任せ"],
  mate: ["mete", "mata"],
  Right: ["Rihgt", "Reght", "Rihgt"],
  言わ: ["告げら", "言", "伝えら", "岩"],
  未知: ["末知", "道", "未曾有"],
  脅威: ["驚異", "脅異", "恐怖"],
  逃げ出さ: ["逃出さ", "逃亡さ", "投げ出さ"],
  立ち向かう: ["太刀向かう", "立向かう", "立向う"],
  遠く: ["遠おく", "遥く", "悠遠"],
  Say: ["Sey", "Seay", "Saey"],
  聞こえる: ["聞える", "聴こえる", "訊こえる"],
  雲: ["霞", "曇", "霧"],
  Fly: ["Fry", "Flay", "Fray"],
  七色: ["虹色", "極彩"],
  Beautiful: [
    "Baeutiful",
    "Beauteful",
    "Beauntiful",
    "Beautifull",
    "Beautyful",
  ],
};
