export const incorrectsDict: { [key: string]: string[] } = {
  can: ["wanna", "gonna"],
  "“SUPERHERO”": ["“SUPARHERO”", "“SUPERHELO”", "“SUPARHELO”"],
  時: ["刻", "時間"],
  飛ん: ["翔ん", "呼ん", "富ん"],
  涙: ["泣", "泪"],
  似合わ: ["相応わ", "以合わ", "位合わ"],
  alright: ["arlight", "alrihgt", "allright"],
  "365": ["364", "366", "345", "356"],
  days: ["dayz", "deys", "day", "dey"],
  "24": ["23", "25", "42"],
  name: ["neme", "nema"],
  歌っ: ["詩っ", "喋っ"],
  踊っ: ["踏っ", "舞っ"],
  肩: ["型", "肘", "堅", "脚"],
  long: ["rong", "lang", "rang"],
  愛: ["恋", "愛情"],
  希望: ["奇望", "願望", "期待"],
  思う: ["思もう", "想もう", "感じる"],
  分かる: ["分る", "解る", "和歌る"],
  守り: ["護もり", "守もり", "真守り"],
  未来: ["将来", "末来", "未頼"],
  嘘: ["虚", "偽"],
  Trust: ["Trast", "Tlast", "Tlust"],
  Gimme: ["Gimmi", "Gemmi", "Gemme"],
  Really: ["Raelly", "Realry", "Rearly"],
  alone: ["arone", "aloun", "aroun"],
  笑顔: ["頬笑", "微笑"],
  強く: ["強よく", "強かに"],
  Call: ["Coll", "Cale", "Cole"],
  call: ["coll", "cale", "cole"],
  雑音: ["難音", "騒音", "喧騒"],
  Break: ["Bleak", "Braek", "Blaek"],
  邪魔: ["妨害", "阻害", "邪馬"],
  奴ら: ["双ら", "奴つら", "奴"],
  Bring: ["Bling"],
  Hang: ["Heng", "Hung"],
  Freak: ["Fleak", "Fleek", "Freek"],
  Wanna: ["Wonna"],
  Gonna: ["Ganna"],
  辛い: ["辛らい", "幸い", "痛い"],
  痛い: ["苦しい", "痛たい", "辛い"],
  全て: ["全べて", "全部"],
  mate: ["mete", "mata", "meta"],
  Right: ["Rihgt", "Light", "Lihgt"],
  言わ: ["怒ら", "威張ら"],
  未知: ["末知", "不明", "見知"],
  脅威: ["驚異", "脅異", "恐怖"],
  逃げ出さ: ["逃出さ", "投げ出さ"],
  立ち向かう: ["太刀向かう", "立向かう", "手向かう"],
  明日: ["朝日", "Earth"],
  Say: ["Sey"],
  聞こえる: ["聞える", "効こえる", "着込める"],
  雲: ["霞", "曇", "霧"],
  Fly: ["Fry", "Flay", "Fray"],
  七色: ["虹色", "極彩"],
  Beautiful: ["Baeutiful", "Beauteful", "Beautifull", "Beautyful"],
};
